### CLASE 1: INTRODUCCION A LA PROGRAMACION EN OCTAVE

- Se plantea un encabezado basico:



In [1]:
clc
clear

- ### Variables

In [2]:
a=1 % se visualiza en la terminal 
b=2; % no se visuaiza en la terminal

format short
pi_aprox=pi % se visualiza en la terminal

format long
pi_aprox2=pi % se visualiza en la terminal

who %variables en el espacio de trabajo
whos %información detallada sobre las variables

a = 1
pi_aprox = 3.1416
pi_aprox2 = 3.141592653589793
Variables visible from the current scope:

a          b          pi_aprox   pi_aprox2

Variables visible from the current scope:

variables in scope: top scope

  Attr   Name           Size                     Bytes  Class
  ====   ====           ====                     =====  ===== 
         a              1x1                          8  double
         b              1x1                          8  double
         pi_aprox       1x1                          8  double
         pi_aprox2      1x1                          8  double

Total is 4 elements using 32 bytes



- ### Operaciones basicas

In [3]:
format short
a= 3.45
b=4.6
c=a+b %suma
d=a-b %resta
e=a*b %multiplicación
f=a/b %división
g=a^b %potencia


a = 3.4500
b = 4.6000
c = 8.0500
d = -1.1500
e = 15.870
f = 0.7500
g = 297.83


- ### Vectores
$ v_{fila}$ \\
$ v_{Columna}$


In [4]:
vfila=[1 2 3] % vecto fila
vcolumna=[1;2;3] % vector columna

vfila =

   1   2   3

vcolumna =

   1
   2
   3



Multiplicacion elemento a elemento.
$V_3=V_1*V_2$

In [5]:
V1=[1 2 3 4 5 6 7 8 9] %vector fila 1
V2=[1 2 3 4 5 6 7 8 9] %vector fila 2

V3=V1.*V2

V1 =

   1   2   3   4   5   6   7   8   9

V2 =

   1   2   3   4   5   6   7   8   9

V3 =

    1    4    9   16   25   36   49   64   81



Multiplicacion escalar
$V_3=V_1 \cdot V_2$

In [6]:
V3=V1*V2' %multiplicación de vectores fila y columna

V3 = 285


- ### Matrices

$$\begin{bmatrix} 
a & b \\ 
c & d 
\end{bmatrix}$$

Definicion de una matriz

In [7]:
A=[1 2;2 3] %matriz 2x2

A =

   1   2
   2   3



Matriz Zeros
$$\begin{bmatrix} 
0 & 0 \\ 
0 & 0 
\end{bmatrix}$$

Matriz unitaria
$$\begin{bmatrix} 
1 & 1 \\ 
1 & 1 
\end{bmatrix}$$

Matriz Identidad
$$\begin{bmatrix} 
1 & 0 \\ 
0 & 1 
\end{bmatrix}$$

In [8]:
Z=zeros(2)% matriz de ceros de nxn

U=ones(2) %matriz unitaria de nxn

I=eye(2) %matriz identidad de nxn




Z =

   0   0
   0   0

U =

   1   1
   1   1

I =

Diagonal Matrix

   1   0
   0   1



- ### Secuencias de numeros 

In [9]:
X=0:0.25:1 %Valor Inicial-Paso-Valor Final
x1=-3:3
Y=linspace(0,1,5) %Valor Inicial-Valor Final-Cantidad de Elementos

X =

         0    0.2500    0.5000    0.7500    1.0000

x1 =

  -3  -2  -1   0   1   2   3

Y =

        0   0.2500   0.5000   0.7500   1.0000



- ### Indexacion de matrices

In [10]:
%Generamos una matriz aleatoria de 8x8
A=magic(5);
R=rand(5); %matriz aleatoria de 8x8

K=A+R

K =

   17.5690   24.2322    1.3880    8.1572   15.7804
   23.0649    5.3219    7.0157   14.6418   16.5807
    4.8717    6.7101   13.6996   20.6174   22.6712
   10.1349   12.2009   19.4459   21.2773    3.6277
   11.2860   18.1499   25.0659    2.4603    9.7645



* Extraccion de Valores de una matriz 

In [11]:
Valor1=K(1,1) %trae el elemento de la primera fila y primera columna
Traza=[K(1,1) K(2,2) K(3,3) K(4,4) K(5,5)] %trae los elementos de la diagonal principal
%Extraemos una fila
Fila1=K(2,:) %trae la segunda fila completa
%Extraemos una columna  
Columna1=K(:,2) %trae la segunda columna completa
%Extraemos una submatriz
SUB1=K(1:3,1:3) %trae la submatriz de 3x3 de la esquina superior izquierda

Valor1 = 17.569
Traza =

   17.5690    5.3219   13.6996   21.2773    9.7645



Fila1 =

   23.0649    5.3219    7.0157   14.6418   16.5807

Columna1 =

   24.2322
    5.3219
    6.7101
   12.2009
   18.1499

SUB1 =

   17.5690   24.2322    1.3880
   23.0649    5.3219    7.0157
    4.8717    6.7101   13.6996



- Introduccion de valores a una matriz

In [12]:
K1=zeros(5)

K1 =

   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0



Introducimos un numero

In [13]:
K1(2,2)=3

K1 =

   0   0   0   0   0
   0   3   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0



Introducimos una matriz

In [14]:
J=[1 -1;
 -1 1]

K1(1:2,1:2)=J(1:2,1:2) %asignamos la submatriz de 3x3 de K a la submatriz de 3x3 de K1

J =

   1  -1
  -1   1

K1 =

   1  -1   0   0   0
  -1   1   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0



## Sentencias de Programacion

### Sentencia IF
Para la ecuacion de segundo grado 

$A\cdot x^2+B\cdot x + C=0$
Se tiene el discriminate:


In [15]:
a=1;
b=2;
c=1;
disc = b ^2 - 4* a*c
if disc > 0
x1 = (-b +sqrt( disc )) / (2* a);
x2 = (-b -sqrt( disc )) / (2* a);
disp(x1)
disp(x2)
disp('Dos raices reales distintas');
elseif disc == 0
x1 = -b / (2* a);
disp(x1)
disp('Una raiz real multiple');
else
disp('Raices complejas');
end


disc = 0
-1
Una raiz real multiple


### Sentencia SWITCH



In [16]:

input('Ingrese el metodo de integración: 1=Trapecio, 2=Simpson, 3=Gaussiana: ');

switch metodo
case 1
disp('RegladelTrapecioSimple');
case 2
disp('RegladeSimpson1/3');
case 3
disp('CuadraturaGaussiana');
otherwise
disp('Metodonumericonoreconocido');
return;%Finalizalaejecucion
end

error: 'metodo' undefined near line 1, column 8


### Sentencia For

$$\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}$$


In [17]:
n=1000;
suma=0; 

%valor de referencia
Sum_exac=pi^2/6

for i=1:n
    suma=suma+1/i^2;
    error=abs(suma-Sum_exac)/Sum_exac*100;
    Lista(i, :) = [i, suma, error];
end
% Encabezados
fprintf('%-8s %-18s %-15s\n', 'n', 'Suma_Acumulada', 'Error');

% Datos (se transpone Lista con ' porque fprintf lee por columnas)
fprintf('%-8d %-18.6f %-15.6f\n', Lista');


Sum_exac = 1.6449
n        Suma_Acumulada     Error          
1        1.000000           39.207290      
2        1.250000           24.009112      
3        1.361111           17.254367      
4        1.423611           13.454822      
5        1.463611           11.023114      
6        1.491389           9.334428       
7        1.511797           8.093760       
8        1.527422           7.143874       
9        1.539768           6.393347       
10       1.549768           5.785419       
11       1.558032           5.283000       
12       1.564977           4.860829       
13       1.570894           4.501109       
14       1.575996           4.190942       
15       1.580440           3.920752       
16       1.584347           3.683280       
17       1.587807           3.472925       
18       1.590893           3.285293       
19       1.593663           3.116892       
20       1.596163           2.964911       
21       1.598431           2.827059       
22       1.600

Sea un polinomio:

$$P(x) = a_n x^n + a_{n-1} x^{n-1} + \cdots + a_1 x + a_0$$

Se puede reescribir mediante el algoritmo de Horner de la siguiente forma anidada para su evauacion 

$$P(x) = a_0 + x \Big( a_1 + x \big( a_2 + \cdots + x(a_{n-1} + x a_n) \cdots \big) \Big)$$

In [18]:
%Vector de coeficientes del polinomio
Coef=[2 3 4]
%Valor mayor del vector de coeficientes
val=Coef(1)

% Punto x donde queremos evaluar el polinomio
x = 1; 
for i = 2:length(Coef)
    val = val * x + Coef(i);
end


Coef =

   2   3   4

val = 2


### Sentencia While

$$\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}$$

In [19]:
% --- 1. CONFIGURACIÓN DE LA COTA DE ERROR ---
tolerancia = 1e-2;          % Cota de error permitida (ej: 0.0001)
valor_teorico = pi^2 / 6;   
format short
suma_acumulada = 0;
n = 1;
error_calculado = valor_teorico; 

Lista=zeros(0,3); % Inicializamos la lista para almacenar los resultados

while error_calculado > tolerancia
    suma_acumulada = suma_acumulada + 1 / (n^2);
      
    error_calculado = abs(valor_teorico - suma_acumulada);
    
    List(n, :) = [n, suma_acumulada, error_calculado];

    % Incrementamos el contador para el siguiente término
    n = n + 1;
end

% Encabezados
fprintf('%-8s %-18s %-15s\n', 'n', 'Suma_Acumulada', 'Error');

% Datos (se transpone Lista con ' porque fprintf lee por columnas)
fprintf('%-8d %-18.6f %-15.6f\n', List');

n        Suma_Acumulada     Error          
1        1.000000           0.644934       
2        1.250000           0.394934       
3        1.361111           0.283823       
4        1.423611           0.221323       
5        1.463611           0.181323       
6        1.491389           0.153545       
7        1.511797           0.133137       
8        1.527422           0.117512       
9        1.539768           0.105166       
10       1.549768           0.095166       
11       1.558032           0.086902       
12       1.564977           0.079957       
13       1.570894           0.074040       
14       1.575996           0.068938       
15       1.580440           0.064494       
16       1.584347           0.060588       
17       1.587807           0.057127       
18       1.590893           0.054041       
19       1.593663           0.051271       
20       1.596163           0.048771       
21       1.598431           0.046503       
22       1.600497           0.04

## SOLUCION DE SISTEMAS DE ECUACIONES POR CHOLESKY

In [20]:
K=[2 -1 0,
  -1  2 -1
   0 -1  1 ]%Matriz de Rigidez

f=[0;0;10]%Vector de fuerzas

U=chol(K)

y=transpose(U)\f %Solucion Triangular Superior
x=U\y

K =

   2  -1   0
  -1   2  -1
   0  -1   1

f =

    0
    0
   10

U =

   1.4142  -0.7071        0
        0   1.2247  -0.8165
        0        0   0.5774

y =

         0
         0
   17.3205

x =

   10
   20
   30



### Implementacion manual del algoritmo de Cholesky

La funcion `chol()` resuelve todo de una vez, pero el metodo se puede programar elemento a elemento con bucles `for` (algoritmo de Cholesky-Banachiewicz), igual que hicimos antes con la suma de la serie:

$$L_{jj}=\sqrt{A_{jj}-\sum_{k=1}^{j-1}L_{jk}^2} \qquad\qquad L_{ij}=\frac{1}{L_{jj}}\left(A_{ij}-\sum_{k=1}^{j-1}L_{ik}L_{jk}\right),\ \ i>j$$

Solo se recorre el triangulo inferior de A porque, al se

In [21]:
%Implementacion manual de Cholesky (algoritmo de Cholesky-Banachiewicz)
A=[2 -1 0;
   -1 2 -1;
    0 -1 1]  %matriz simetrica definida positiva (ejemplo clasico)

n=size(A,1);
L=zeros(n);

for i=1:n
    for j=1:i
        suma=0;
        for k=1:j-1
            suma=suma+L(i,k)*L(j,k);
        end
        if i==j
            L(i,j)=sqrt(A(i,i)-suma);
        else
            L(i,j)=(A(i,j)-suma)/L(j,j);
        end
    end
end

L  %factor triangular inferior calculado manualmente

%Verificacion contra la funcion nativa de Octave
L_octave=chol(A)'  %chol() devuelve el triangular superior U, por eso se transpone

error_max=max(max(abs(L-L_octave)))  %debe ser practicamente cer

A =

   2  -1   0
  -1   2  -1
   0  -1   1

L =

   1.4142        0        0
  -0.7071   1.2247        0
        0  -0.8165   0.5774

L_octave =

   1.4142        0        0
  -0.7071   1.2247        0
        0  -0.8165   0.5774

error_max = 0


### IMPLEMENTACION ALGORITMO DE INTEGRACION TRAPECIO

In [22]:
% Ejemplo: integral de sin(x) entre 0 y pi (valor exacto = 2)

f = @(x) sin(x);   % funcion a integrar
a = 0;             % limite inferior
b = pi;            % limite superior
n = 100;           % numero de subintervalos

h = (b - a) / n;

% Calculamos los puntos x(i) con un for
x = zeros(1, n+1);
for i = 1:n+1
    x(i) = a + (i-1)*h;
end

% Evaluamos la funcion en cada punto con un for
y = zeros(1, n+1);
for i = 1:n+1
    y(i) = f(x(i));
end

% Sumamos los terminos intermedios con un for
suma = 0;
for i = 2:n
    suma = suma + y(i);
end

I = (h/2) * (y(1) + 2*suma + y(n+1));

printf("Integral aproximada (trapecio): %f\n", I);
printf("Valor exacto: %f\n", 2);
printf("Error: %e\n", abs(I - 2));


Integral aproximada (trapecio): 1.999836
Valor exacto: 2.000000
Error: 1.644961e-04
