### CLASE 1-METODO DE ELEMENTOS FINITOS

In [49]:
clc
clear

- ### VARIABLES
Visualizacion de variables

In [50]:
a=1 %los valores se visualizan en la terminal
b=2; %Los valores no se visualizan en la terminal

a = 1


In [51]:
format short
pi_aprx1=pi % aproximación con 4 cifras significativas

format long
pi_aprx2=pi %aproximacion 16 cifras significativas

pi_aprx1 = 3.1416
pi_aprx2 = 3.141592653589793


In [52]:
who
whos

Variables visible from the current scope:

a         b         pi_aprx1  pi_aprx2

Variables visible from the current scope:

variables in scope: top scope

  Attr   Name          Size                     Bytes  Class
  ====   ====          ====                     =====  ===== 
         a             1x1                          8  double
         b             1x1                          8  double
         pi_aprx1      1x1                          8  double
         pi_aprx2      1x1                          8  double

Total is 4 elements using 32 bytes



- ### OPERACIONES BASICAS

In [53]:
format short
a=3.45
c=4.60

%Se define las operaciones basicas

c=a+b
d=a-b
e=a*b
f=a/b
g=a^b



a = 3.4500
c = 4.6000
c = 5.4500
d = 1.4500
e = 6.9000
f = 1.7250
g = 11.903


Calcular la operacion:
$$ (1 + 2^4)^2 \cdot \frac{7^3}{4^2 - 1} $$

In [54]:
A=((1+2^2)^2)*7^3/(4^2-1);
disp("El resultado de A es: "),disp(A)

El resultado de A es: 
571.67


- ### DEFINICION DE VECTORES
Vectores fila
$V_{FILA}$
Vectores Columna
$V_{COLUMNA}$



In [55]:
%Vector fila
v_fila=[1 2 3 4 5]
%vector columna
v_columna=[1;2;3;4;5]

v_fila =

   1   2   3   4   5

v_columna =

   1
   2
   3
   4
   5



Operaciones Basicas con vectores

In [56]:
V1= [1 2 3 4 5];
V2=[7 8 9 10 11];
V22=[7; 8; 9; 10; 11];

V3=V1+V2 %suma elemento a elemento 
V4=V1.*V2 %multiplicacion elemento a elemento

V5=V1*transpose(V2) % multiplicacion de vectores, el resultado es un escalar

V6=V1*V22

N=length(V1)


V3 =

    8   10   12   14   16

V4 =

    7   16   27   40   55

V5 = 145
V6 = 145
N = 5


- ### MATRICES
Matriz general
$$ \begin{bmatrix} a_{11} & a_{12} \\  a_{21}& a_{22} \end{bmatrix} $$

Matriz nula 
$$ \begin{bmatrix} 0& 0 \\  0& 0 \end{bmatrix} $$

Matriz unitaria
$$ \begin{bmatrix} 1& 1 \\  1& 1 \end{bmatrix} $$

Matriz Identidad
$$ \begin{bmatrix} 1& 0 \\  0& 1 \end{bmatrix} $$

In [57]:
% Matriz de 2x2
K=[1 -1;
   -1 1]

%matriz nula 
K1=zeros(2)

%matriz unitaria
K2=ones(2)

%Matriz identidad
K3=eye(2)


K =

   1  -1
  -1   1

K1 =

   0   0
   0   0

K2 =

   1   1
   1   1

K3 =

Diagonal Matrix

   1   0
   0   1



-Indexacion matricial

In [58]:
M=magic(5)
L=rand(5)
S=M+L

M =

   17   24    1    8   15
   23    5    7   14   16
    4    6   13   20   22
   10   12   19   21    3
   11   18   25    2    9

L =

   0.451565   0.167450   0.518971   0.954547   0.952694
   0.581719   0.711011   0.677353   0.312204   0.964338
   0.221022   0.392824   0.377525   0.151787   0.164489
   0.145989   0.802677   0.883488   0.937922   0.069673
   0.272583   0.395623   0.422801   0.915012   0.865480

S =

   17.4516   24.1674    1.5190    8.9545   15.9527
   23.5817    5.7110    7.6774   14.3122   16.9643
    4.2210    6.3928   13.3775   20.1518   22.1645
   10.1460   12.8027   19.8835   21.9379    3.0697
   11.2726   18.3956   25.4228    2.9150    9.8655



In [59]:
%Extraccion de elementos de una matriz

A_1=S(3,3) %Extraer un valor de la matriz
F_1=S(4,:) %Extraer una fila de la matriz
C_1=S(:,5) %Extraer una columna de la matriz
SM_1=S(3:5,1:2)


A_1 = 13.378
F_1 =

   10.1460   12.8027   19.8835   21.9379    3.0697

C_1 =

   15.9527
   16.9643
   22.1645
    3.0697
    9.8655

SM_1 =

    4.2210    6.3928
   10.1460   12.8027
   11.2726   18.3956



In [60]:
Z=zeros(5) %Matriz de ceros de 3x4

Z =

   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0



In [61]:
Z(3,3)=5.63

Z =

        0        0        0        0        0
        0        0        0        0        0
        0        0   5.6300        0        0
        0        0        0        0        0
        0        0        0        0        0



In [62]:
k=[1 -1
 -1 1]

 Z(1:2,1:2)=k

 Z(2:3,2:3)=k

k =

   1  -1
  -1   1

Z =

   1.0000  -1.0000        0        0        0
  -1.0000   1.0000        0        0        0
        0        0   5.6300        0        0
        0        0        0        0        0
        0        0        0        0        0

Z =

   1  -1   0   0   0
  -1   1  -1   0   0
   0  -1   1   0   0
   0   0   0   0   0
   0   0   0   0   0



## - SENTENCIAS DE PROGRAMACION

### Sentencia IF

In [63]:
%Coeficientes del polinomio de segundo grado
a=1;
b=7;
c=1;
% Calculo el discriminante
disc = b ^2 - 4* a*c

%Bloque de condicion 
if disc > 0
    x1 = (-b +sqrt( disc )) / (2* a);
    x2 = (-b -sqrt( disc )) / (2* a);
    disp(x1)
    disp(x2)
    disp('Dos raices reales distintas')

    elseif disc == 0
        x1 = -b / (2* a);
        disp(x1)
        disp('Una raiz real multiple')
    else
        disp('Raices complejas')
end

disc = 45
-0.1459
-6.8541
Dos raices reales distintas


### Sentencia FOR
$$ \sum_{n=1}^{\N} \frac{1}{n^2} = \frac{\pi^2}{6} $$


In [64]:
n=100000;
suma=0;
%valor de referencia
Sum_exac=pi^2/6

for i=1:n
suma=suma+1/i^2;
end
suma
error=(abs(Sum_exac-suma)/Sum_exac)*100


Sum_exac = 1.6449
suma = 1.6449
error = 6.0792e-04


In [65]:
n=3; %elementos matriciales


for i=1:n
K=[1*i -i;-i i]
end


K =

   1  -1
  -1   1

K =

   2  -2
  -2   2

K =

   3  -3
  -3   3

